### ISSUE TITLE
Document PHP iconv Requirement

### ISSUE THREAD

**Issue by austinbutler** [Sommerregen/grav-plugin-toc#1]
Got a "call to undefined function" for iconv after installing, had to uncomment it in my php.ini file and restart PHP.

**Comment by Sommerregen** [comment]
Hi @austinbutler ,

good idea! I will add it to the docs. And yeah **Toc** uses iconv module to transliterate titles into machine readable slugs.

Thanks :+1:

**Comment by Sommerregen** [comment]
Done.
