### ISSUE TITLE
QuoteBoxes Break Links in TOC

### ISSUE THREAD

**Issue by ghost** [Sommerregen/grav-plugin-toc#10]
Greetings,

I just noticed that QuoteBoxes break the links to the anchors within the Table of Contents. See my attachment for a better explaination.

I have circled the QuoteBox (in Red) and highlighted the links (in Yellow) to the right that don't function. Where the QuoteBox resides, all links to the right do not work. Those links to the right, above and below the QuoteBox, work as normal.

Thanks!
Brian U.

![screen shot 2016-02-03 at 3 55 55 am](https://cloud.githubusercontent.com/assets/5008228/12779016/65e2e036-ca2b-11e5-943f-eea1f36bdc50.png)

**Comment by Sommerregen** [comment]
That is a bug and is because due to some CSS styling (more specifically the `position: relative` option) and the quote box is actually overlaying the TOC bar. Giving a higher `z-index` should resolve the issue.

**Comment by Sommerregen** [comment]
This is an old issue and should not happen anymore with the latest release **v1.4.0**.
