### ISSUE TITLE
[MINITOC] fails with an PHP exception.

### ISSUE THREAD

**Issue by beijersb** [Sommerregen/grav-plugin-toc#12]
Just installed TOC on a fresh 1.1.0 Grav instance and added [MINITOC] to my page. It crashes with an exception:
![schermafbeelding 2016-07-15 om 09 21 44](https://cloud.githubusercontent.com/assets/4711779/16866744/05ef912e-4a6e-11e6-90b5-606bd85ba3fb.png)
I will look into the matter and update this issue accordingly.

Using [TOC] yields the expected result.

**Comment by Sommerregen** [comment]
This is because in some cases `$current` equals `-1`, which throws this error. I have pushed a fix and will test it thoroughly in the next days.

**Comment by Lamecarlate** [comment]
Hi, this fix has not been released, it seems: the last version is 1.3.1, october 2015. Do you plan to do a full release soon?

**Comment by Sommerregen** [comment]
Hi @Lamecarlate , it's on my list now. I will carefully test the plugin during the weekends and will release a new version.

**Comment by Lamecarlate** [comment]
Thank you!
