### ISSUE TITLE
Not working with Grav's Admin Panel

### ISSUE THREAD

**Issue by jpfleury** [Sommerregen/grav-plugin-toc#2]
The plugin Toc can't be configured using the new [Grav's Admin Panel](https://github.com/getgrav/grav-plugin-admin). For example, if we go to the settings page of the plugin (url `/admin/plugins/toc`) and click on _Save_, there's the following error:

> **Validation failed:** visible is not defined in blueprints

According to a Grav developer: "These plugins just need to get updated with appropriate blueprint files so they will work in the admin plugin."

My config: Grav v0.9.39, Admin Panel v0.4.2, Toc v1.2.0

**Comment by Sommerregen** [comment]
Ok, thanks :+1: This will be fixed in the next release.

**Comment by Sommerregen** [comment]
Fixed with latest release.
