### ISSUE TITLE
fontawesome icons double links

### ISSUE THREAD

**Issue by fugo** [Sommerregen/grav-plugin-toc#29]
I use icons (fontawesome) in my headers and get this:

```html
     <li><a href="#fa-icon-fa-file-signature..." class="toclink" title="<i class="fad fa-file-signature"></i> How can I control cookies?"><i class="fad fa-file-signature"></i> How can I control cookies?</a></li>
```
![part of menu](https://i.imgur.com/G9dvls4.png)

How can I avoid this?
Thank you for any idea.

**Comment by CarlSinclair** [comment]
How did you make icons work? I can't even make markdown escape in the toc, let alone html

**Comment by fugo** [comment]
I don't use it anymore – Sorry

**Comment by CarlSinclair** [comment]
I figured it out, in case anyone finds this. You can't just tell it to process markdown because that will also make it process some invisible white space like new lines. This code fixes both problems:

```{# Show TOC link based on anchorlinks option #}
{% if toc.anchorlink %}
    <li><a href="#{{ entry.id|e('html_attr') }}" class="toclink" title="{{ entry.text|striptags|replace({'\r\n': '', '\n': '', '\r': ''}) }}">{{ entry.text|replace({'\r\n': '', '\n': '', '\r': ''})|raw }}</a></li>
{% else %}
    <li><span class="toclink">{{ entry.text|replace({'\r\n': '', '\n': '', '\r': ''})|raw }}</span></li>
{% endif %}
```
