### ISSUE TITLE
Do not render the TOC if it is empty

### ISSUE THREAD

**Issue by tomzx** [Sommerregen/grav-plugin-toc#6]
I have a blog where I force the TOC to render since the [TOC] macro is not part of the article's content.

```
{{ ('<p>[TOC]</p>'~page.content)|toc }}
```

However, I'd like it if the TOC didn't render anything if the table was empty. Is there any way to make that possible?

Thanks!

**Comment by Sommerregen** [comment]
HI @tomzx , I guess that's something I have to update. Instead of [L251](https://github.com/Sommerregen/grav-plugin-toc/blob/master/classes/Toc.php#L251) you may try this (untested).

``` php
$toc = $this->createToc($content);
// Don't process TOC if there aren't any headings in the content
if (empty($toc)) {
  return $content;
}
```

**Comment by tomzx** [comment]
@Sommerregen Thanks!
